/**
 * OpenAI Service for generating images based on descriptions
 * Uses OpenAI's DALL-E model for image generation
 */
import OpenAI from "openai";
import { Candidate } from "@shared/schema";

// Initialize OpenAI client with API key
const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

/**
 * Generate a caricature image based on a description
 * @param candidate The candidate object
 * @param description The description generated by Grok
 * @returns Base64 encoded image data
 */
export async function generateCaricatureImage(
  candidate: Candidate,
  description: string
): Promise<string | null> {
  try {
    console.log(`Generating caricature image for ${candidate.name} using DALL-E...`);
    
    // Create an optimized prompt for DALL-E based on the description
    // We need to make it more concise and focused on the visual aspects
    const enhancedPrompt = `
      Create a political caricature in cartoon style of Australian politician ${candidate.name} 
      from the ${candidate.partyBallotName || 'Independent'} party.
      
      Based on this description: ${description.substring(0, 700)}
      
      Style: Classic political cartoon with exaggerated features, bright colors, clean lines
      Background: Include subtle Australian elements
      Format: Digital illustration with white background
    `;
    
    // Generate the image using the new GPT-4 image generation model
    const response = await openai.images.generate({
      model: "gpt-4-vision-preview",  // Using the newer GPT-4 image model
      prompt: enhancedPrompt.trim(),
      n: 1,
      size: "1024x1024",
      quality: "hd",
      response_format: "b64_json", // Get base64 encoded image directly
    });
    
    // Extract the base64 image data
    if (response.data && response.data.length > 0 && response.data[0].b64_json) {
      console.log(`Successfully generated caricature image for ${candidate.name}`);
      return response.data[0].b64_json;
    } else {
      console.error(`No image data returned for ${candidate.name}`);
      return null;
    }
  } catch (error) {
    console.error(`Error generating caricature image for ${candidate.name}:`, error);
    return null;
  }
}

// Default export for the OpenAI service
export default {
  generateCaricatureImage
};